//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//havli//source//repos//ClosedXML.Parser//src//ClosedXML.ANTLR//FormulaParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


// ANTLR generated file is marked as a non-CLS compliant, but that is not necessary, because whole assembly is not CLS compliant.
#pragma warning disable 3021

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class FormulaParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		REF_CONSTANT=1, NONREF_ERRORS=2, LOGICAL_CONSTANT=3, NUMERICAL_CONSTANT=4, 
		STRING_CONSTANT=5, POW=6, MULT=7, DIV=8, PLUS=9, MINUS=10, CONCAT=11, 
		EQUAL=12, NOT_EQUAL=13, LESS_OR_EQUAL_THAN=14, LESS_THAN=15, GREATER_OR_EQUAL_THAN=16, 
		GREATER_THAN=17, PERCENT=18, SEMICOLON=19, COLON=20, OPEN_BRACE=21, CLOSE_BRACE=22, 
		OPEN_CURLY=23, CLOSE_CURLY=24, COMMA=25, SPACE=26, INTERSECT=27, SPILL=28, 
		BOOK_PREFIX=29, BANG_REFERENCE=30, SHEET_RANGE_PREFIX=31, SINGLE_SHEET_PREFIX=32, 
		A1_CELL=33, A1_SPAN_REFERENCE=34, REF_FUNCTION_LIST=35, CELL_FUNCTION_LIST=36, 
		USER_DEFINED_FUNCTION_NAME=37, NAME=38, INTRA_TABLE_REFERENCE=39, DDE_ITEM=40, 
		BANG_NAME=41;
	public const int
		RULE_formula = 0, RULE_expression = 1, RULE_concat_expression = 2, RULE_additive_expression = 3, 
		RULE_multiplying_expression = 4, RULE_pow_expression = 5, RULE_percent_expression = 6, 
		RULE_prefix_atom_expression = 7, RULE_atom_expression = 8, RULE_ref_expression = 9, 
		RULE_ref_implicit_expression = 10, RULE_ref_intersection_expression = 11, 
		RULE_ref_range_expression = 12, RULE_ref_spill_expression = 13, RULE_ref_atom_expression = 14, 
		RULE_constant = 15, RULE_constant_list_rows = 16, RULE_constant_list_row = 17, 
		RULE_cell_reference = 18, RULE_a1_reference = 19, RULE_argument_list = 20, 
		RULE_arg_expression = 21, RULE_arg_concat_expression = 22, RULE_arg_additive_expression = 23, 
		RULE_arg_multiplying_expression = 24, RULE_arg_pow_expression = 25, RULE_arg_percent_expression = 26, 
		RULE_arg_prefix_atom_expression = 27, RULE_arg_atom_expression = 28, RULE_name_reference = 29, 
		RULE_dde_reference = 30, RULE_structure_reference = 31, RULE_table_identifier = 32, 
		RULE_table_name = 33, RULE_ref_function_call = 34, RULE_function_call = 35;
	public static readonly string[] ruleNames = {
		"formula", "expression", "concat_expression", "additive_expression", "multiplying_expression", 
		"pow_expression", "percent_expression", "prefix_atom_expression", "atom_expression", 
		"ref_expression", "ref_implicit_expression", "ref_intersection_expression", 
		"ref_range_expression", "ref_spill_expression", "ref_atom_expression", 
		"constant", "constant_list_rows", "constant_list_row", "cell_reference", 
		"a1_reference", "argument_list", "arg_expression", "arg_concat_expression", 
		"arg_additive_expression", "arg_multiplying_expression", "arg_pow_expression", 
		"arg_percent_expression", "arg_prefix_atom_expression", "arg_atom_expression", 
		"name_reference", "dde_reference", "structure_reference", "table_identifier", 
		"table_name", "ref_function_call", "function_call"
	};

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "REF_CONSTANT", "NONREF_ERRORS", "LOGICAL_CONSTANT", "NUMERICAL_CONSTANT", 
		"STRING_CONSTANT", "POW", "MULT", "DIV", "PLUS", "MINUS", "CONCAT", "EQUAL", 
		"NOT_EQUAL", "LESS_OR_EQUAL_THAN", "LESS_THAN", "GREATER_OR_EQUAL_THAN", 
		"GREATER_THAN", "PERCENT", "SEMICOLON", "COLON", "OPEN_BRACE", "CLOSE_BRACE", 
		"OPEN_CURLY", "CLOSE_CURLY", "COMMA", "SPACE", "INTERSECT", "SPILL", "BOOK_PREFIX", 
		"BANG_REFERENCE", "SHEET_RANGE_PREFIX", "SINGLE_SHEET_PREFIX", "A1_CELL", 
		"A1_SPAN_REFERENCE", "REF_FUNCTION_LIST", "CELL_FUNCTION_LIST", "USER_DEFINED_FUNCTION_NAME", 
		"NAME", "INTRA_TABLE_REFERENCE", "DDE_ITEM", "BANG_NAME"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FormulaParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static FormulaParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FormulaParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public FormulaParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FormulaContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(FormulaParser.Eof, 0); }
		public FormulaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formula; } }
	}

	[RuleVersion(0)]
	public FormulaContext formula() {
		FormulaContext _localctx = new FormulaContext(Context, State);
		EnterRule(_localctx, 0, RULE_formula);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			expression();
			State = 73;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Concat_expressionContext[] concat_expression() {
			return GetRuleContexts<Concat_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Concat_expressionContext concat_expression(int i) {
			return GetRuleContext<Concat_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_OR_EQUAL_THAN() { return GetTokens(FormulaParser.GREATER_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.GREATER_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_OR_EQUAL_THAN() { return GetTokens(FormulaParser.LESS_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.LESS_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_THAN() { return GetTokens(FormulaParser.LESS_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_THAN(int i) {
			return GetToken(FormulaParser.LESS_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_THAN() { return GetTokens(FormulaParser.GREATER_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_THAN(int i) {
			return GetToken(FormulaParser.GREATER_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NOT_EQUAL() { return GetTokens(FormulaParser.NOT_EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT_EQUAL(int i) {
			return GetToken(FormulaParser.NOT_EQUAL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] EQUAL() { return GetTokens(FormulaParser.EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL(int i) {
			return GetToken(FormulaParser.EQUAL, i);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 2, RULE_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			concat_expression();
			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) {
				{
				{
				State = 76;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 77;
				concat_expression();
				}
				}
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Concat_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Additive_expressionContext[] additive_expression() {
			return GetRuleContexts<Additive_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Additive_expressionContext additive_expression(int i) {
			return GetRuleContext<Additive_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CONCAT() { return GetTokens(FormulaParser.CONCAT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONCAT(int i) {
			return GetToken(FormulaParser.CONCAT, i);
		}
		public Concat_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_concat_expression; } }
	}

	[RuleVersion(0)]
	public Concat_expressionContext concat_expression() {
		Concat_expressionContext _localctx = new Concat_expressionContext(Context, State);
		EnterRule(_localctx, 4, RULE_concat_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			additive_expression();
			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CONCAT) {
				{
				{
				State = 84;
				Match(CONCAT);
				State = 85;
				additive_expression();
				}
				}
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Additive_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Multiplying_expressionContext[] multiplying_expression() {
			return GetRuleContexts<Multiplying_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Multiplying_expressionContext multiplying_expression(int i) {
			return GetRuleContext<Multiplying_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PLUS() { return GetTokens(FormulaParser.PLUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS(int i) {
			return GetToken(FormulaParser.PLUS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MINUS() { return GetTokens(FormulaParser.MINUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS(int i) {
			return GetToken(FormulaParser.MINUS, i);
		}
		public Additive_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additive_expression; } }
	}

	[RuleVersion(0)]
	public Additive_expressionContext additive_expression() {
		Additive_expressionContext _localctx = new Additive_expressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_additive_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			multiplying_expression();
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PLUS || _la==MINUS) {
				{
				{
				State = 92;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 93;
				multiplying_expression();
				}
				}
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Multiplying_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Pow_expressionContext[] pow_expression() {
			return GetRuleContexts<Pow_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pow_expressionContext pow_expression(int i) {
			return GetRuleContext<Pow_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MULT() { return GetTokens(FormulaParser.MULT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT(int i) {
			return GetToken(FormulaParser.MULT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DIV() { return GetTokens(FormulaParser.DIV); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV(int i) {
			return GetToken(FormulaParser.DIV, i);
		}
		public Multiplying_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplying_expression; } }
	}

	[RuleVersion(0)]
	public Multiplying_expressionContext multiplying_expression() {
		Multiplying_expressionContext _localctx = new Multiplying_expressionContext(Context, State);
		EnterRule(_localctx, 8, RULE_multiplying_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			pow_expression();
			State = 104;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==MULT || _la==DIV) {
				{
				{
				State = 100;
				_la = TokenStream.LA(1);
				if ( !(_la==MULT || _la==DIV) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 101;
				pow_expression();
				}
				}
				State = 106;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pow_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Percent_expressionContext[] percent_expression() {
			return GetRuleContexts<Percent_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Percent_expressionContext percent_expression(int i) {
			return GetRuleContext<Percent_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] POW() { return GetTokens(FormulaParser.POW); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POW(int i) {
			return GetToken(FormulaParser.POW, i);
		}
		public Pow_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pow_expression; } }
	}

	[RuleVersion(0)]
	public Pow_expressionContext pow_expression() {
		Pow_expressionContext _localctx = new Pow_expressionContext(Context, State);
		EnterRule(_localctx, 10, RULE_pow_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 107;
			percent_expression();
			State = 112;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==POW) {
				{
				{
				State = 108;
				Match(POW);
				State = 109;
				percent_expression();
				}
				}
				State = 114;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Percent_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Prefix_atom_expressionContext prefix_atom_expression() {
			return GetRuleContext<Prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PERCENT() { return GetTokens(FormulaParser.PERCENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PERCENT(int i) {
			return GetToken(FormulaParser.PERCENT, i);
		}
		public Percent_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_percent_expression; } }
	}

	[RuleVersion(0)]
	public Percent_expressionContext percent_expression() {
		Percent_expressionContext _localctx = new Percent_expressionContext(Context, State);
		EnterRule(_localctx, 12, RULE_percent_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115;
			prefix_atom_expression();
			State = 119;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PERCENT) {
				{
				{
				State = 116;
				Match(PERCENT);
				}
				}
				State = 121;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prefix_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Prefix_atom_expressionContext prefix_atom_expression() {
			return GetRuleContext<Prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(FormulaParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(FormulaParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Atom_expressionContext atom_expression() {
			return GetRuleContext<Atom_expressionContext>(0);
		}
		public Prefix_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prefix_atom_expression; } }
	}

	[RuleVersion(0)]
	public Prefix_atom_expressionContext prefix_atom_expression() {
		Prefix_atom_expressionContext _localctx = new Prefix_atom_expressionContext(Context, State);
		EnterRule(_localctx, 14, RULE_prefix_atom_expression);
		int _la;
		try {
			State = 125;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 122;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 123;
				prefix_atom_expression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 124;
				atom_expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext constant() {
			return GetRuleContext<ConstantContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_BRACE() { return GetToken(FormulaParser.OPEN_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Function_callContext function_call() {
			return GetRuleContext<Function_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_expressionContext ref_expression() {
			return GetRuleContext<Ref_expressionContext>(0);
		}
		public Atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom_expression; } }
	}

	[RuleVersion(0)]
	public Atom_expressionContext atom_expression() {
		Atom_expressionContext _localctx = new Atom_expressionContext(Context, State);
		EnterRule(_localctx, 16, RULE_atom_expression);
		try {
			State = 134;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 127;
				constant();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 128;
				Match(OPEN_BRACE);
				State = 129;
				expression();
				State = 130;
				Match(CLOSE_BRACE);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 132;
				function_call();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 133;
				ref_expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext[] ref_implicit_expression() {
			return GetRuleContexts<Ref_implicit_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression(int i) {
			return GetRuleContext<Ref_implicit_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(FormulaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(FormulaParser.COMMA, i);
		}
		public Ref_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_expression; } }
	}

	[RuleVersion(0)]
	public Ref_expressionContext ref_expression() {
		Ref_expressionContext _localctx = new Ref_expressionContext(Context, State);
		EnterRule(_localctx, 18, RULE_ref_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136;
			ref_implicit_expression();
			State = 141;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 137;
				Match(COMMA);
				State = 138;
				ref_implicit_expression();
				}
				}
				State = 143;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_implicit_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTERSECT() { return GetToken(FormulaParser.INTERSECT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression() {
			return GetRuleContext<Ref_implicit_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_intersection_expressionContext ref_intersection_expression() {
			return GetRuleContext<Ref_intersection_expressionContext>(0);
		}
		public Ref_implicit_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_implicit_expression; } }
	}

	[RuleVersion(0)]
	public Ref_implicit_expressionContext ref_implicit_expression() {
		Ref_implicit_expressionContext _localctx = new Ref_implicit_expressionContext(Context, State);
		EnterRule(_localctx, 20, RULE_ref_implicit_expression);
		try {
			State = 147;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 144;
				Match(INTERSECT);
				State = 145;
				ref_implicit_expression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 146;
				ref_intersection_expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_intersection_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_range_expressionContext[] ref_range_expression() {
			return GetRuleContexts<Ref_range_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_range_expressionContext ref_range_expression(int i) {
			return GetRuleContext<Ref_range_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(FormulaParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(FormulaParser.SPACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTERSECT() { return GetToken(FormulaParser.INTERSECT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression() {
			return GetRuleContext<Ref_implicit_expressionContext>(0);
		}
		public Ref_intersection_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_intersection_expression; } }
	}

	[RuleVersion(0)]
	public Ref_intersection_expressionContext ref_intersection_expression() {
		Ref_intersection_expressionContext _localctx = new Ref_intersection_expressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_ref_intersection_expression);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 149;
			ref_range_expression();
			State = 154;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 150;
					Match(SPACE);
					State = 151;
					ref_range_expression();
					}
					} 
				}
				State = 156;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			State = 160;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				{
				State = 157;
				if (!(IsSpaceBeforeAt(CurrentToken.Text))) throw new FailedPredicateException(this, "IsSpaceBeforeAt(CurrentToken.Text)");
				State = 158;
				Match(INTERSECT);
				State = 159;
				ref_implicit_expression();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_range_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_spill_expressionContext[] ref_spill_expression() {
			return GetRuleContexts<Ref_spill_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_spill_expressionContext ref_spill_expression(int i) {
			return GetRuleContext<Ref_spill_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COLON() { return GetTokens(FormulaParser.COLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON(int i) {
			return GetToken(FormulaParser.COLON, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTERSECT() { return GetToken(FormulaParser.INTERSECT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression() {
			return GetRuleContext<Ref_implicit_expressionContext>(0);
		}
		public Ref_range_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_range_expression; } }
	}

	[RuleVersion(0)]
	public Ref_range_expressionContext ref_range_expression() {
		Ref_range_expressionContext _localctx = new Ref_range_expressionContext(Context, State);
		EnterRule(_localctx, 24, RULE_ref_range_expression);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 162;
			ref_spill_expression();
			State = 167;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 163;
					Match(COLON);
					State = 164;
					ref_spill_expression();
					}
					} 
				}
				State = 169;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			State = 173;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 170;
				Match(COLON);
				State = 171;
				Match(INTERSECT);
				State = 172;
				ref_implicit_expression();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_spill_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_atom_expressionContext ref_atom_expression() {
			return GetRuleContext<Ref_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPILL() { return GetToken(FormulaParser.SPILL, 0); }
		public Ref_spill_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_spill_expression; } }
	}

	[RuleVersion(0)]
	public Ref_spill_expressionContext ref_spill_expression() {
		Ref_spill_expressionContext _localctx = new Ref_spill_expressionContext(Context, State);
		EnterRule(_localctx, 26, RULE_ref_spill_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 175;
			ref_atom_expression();
			State = 177;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				{
				State = 176;
				Match(SPILL);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] REF_CONSTANT() { return GetTokens(FormulaParser.REF_CONSTANT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_CONSTANT(int i) {
			return GetToken(FormulaParser.REF_CONSTANT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public A1_referenceContext a1_reference() {
			return GetRuleContext<A1_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_BRACE() { return GetToken(FormulaParser.OPEN_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Ref_expressionContext ref_expression() {
			return GetRuleContext<Ref_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Cell_referenceContext cell_reference() {
			return GetRuleContext<Cell_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_function_callContext ref_function_call() {
			return GetRuleContext<Ref_function_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Name_referenceContext name_reference() {
			return GetRuleContext<Name_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Structure_referenceContext structure_reference() {
			return GetRuleContext<Structure_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Dde_referenceContext dde_reference() {
			return GetRuleContext<Dde_referenceContext>(0);
		}
		public Ref_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_atom_expression; } }
	}

	[RuleVersion(0)]
	public Ref_atom_expressionContext ref_atom_expression() {
		Ref_atom_expressionContext _localctx = new Ref_atom_expressionContext(Context, State);
		EnterRule(_localctx, 28, RULE_ref_atom_expression);
		try {
			State = 193;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 179;
				Match(REF_CONSTANT);
				State = 182;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
				case 1:
					{
					State = 180;
					a1_reference();
					}
					break;
				case 2:
					{
					State = 181;
					Match(REF_CONSTANT);
					}
					break;
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 184;
				Match(OPEN_BRACE);
				State = 185;
				ref_expression();
				State = 186;
				Match(CLOSE_BRACE);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 188;
				cell_reference();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 189;
				ref_function_call();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 190;
				name_reference();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 191;
				structure_reference();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 192;
				dde_reference();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstantContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NONREF_ERRORS() { return GetToken(FormulaParser.NONREF_ERRORS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LOGICAL_CONSTANT() { return GetToken(FormulaParser.LOGICAL_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMERICAL_CONSTANT() { return GetToken(FormulaParser.NUMERICAL_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_CONSTANT() { return GetToken(FormulaParser.STRING_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_CURLY() { return GetToken(FormulaParser.OPEN_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Constant_list_rowsContext constant_list_rows() {
			return GetRuleContext<Constant_list_rowsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_CURLY() { return GetToken(FormulaParser.CLOSE_CURLY, 0); }
		public ConstantContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant; } }
	}

	[RuleVersion(0)]
	public ConstantContext constant() {
		ConstantContext _localctx = new ConstantContext(Context, State);
		EnterRule(_localctx, 30, RULE_constant);
		try {
			State = 203;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NONREF_ERRORS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 195;
				Match(NONREF_ERRORS);
				}
				break;
			case LOGICAL_CONSTANT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 196;
				Match(LOGICAL_CONSTANT);
				}
				break;
			case NUMERICAL_CONSTANT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 197;
				Match(NUMERICAL_CONSTANT);
				}
				break;
			case STRING_CONSTANT:
				EnterOuterAlt(_localctx, 4);
				{
				State = 198;
				Match(STRING_CONSTANT);
				}
				break;
			case OPEN_CURLY:
				EnterOuterAlt(_localctx, 5);
				{
				State = 199;
				Match(OPEN_CURLY);
				State = 200;
				constant_list_rows();
				State = 201;
				Match(CLOSE_CURLY);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Constant_list_rowsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Constant_list_rowContext[] constant_list_row() {
			return GetRuleContexts<Constant_list_rowContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Constant_list_rowContext constant_list_row(int i) {
			return GetRuleContext<Constant_list_rowContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMICOLON() { return GetTokens(FormulaParser.SEMICOLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON(int i) {
			return GetToken(FormulaParser.SEMICOLON, i);
		}
		public Constant_list_rowsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant_list_rows; } }
	}

	[RuleVersion(0)]
	public Constant_list_rowsContext constant_list_rows() {
		Constant_list_rowsContext _localctx = new Constant_list_rowsContext(Context, State);
		EnterRule(_localctx, 32, RULE_constant_list_rows);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 205;
			constant_list_row();
			State = 210;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SEMICOLON) {
				{
				{
				State = 206;
				Match(SEMICOLON);
				State = 207;
				constant_list_row();
				}
				}
				State = 212;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Constant_list_rowContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext[] constant() {
			return GetRuleContexts<ConstantContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext constant(int i) {
			return GetRuleContext<ConstantContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] REF_CONSTANT() { return GetTokens(FormulaParser.REF_CONSTANT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_CONSTANT(int i) {
			return GetToken(FormulaParser.REF_CONSTANT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(FormulaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(FormulaParser.COMMA, i);
		}
		public Constant_list_rowContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant_list_row; } }
	}

	[RuleVersion(0)]
	public Constant_list_rowContext constant_list_row() {
		Constant_list_rowContext _localctx = new Constant_list_rowContext(Context, State);
		EnterRule(_localctx, 34, RULE_constant_list_row);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 215;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NONREF_ERRORS:
			case LOGICAL_CONSTANT:
			case NUMERICAL_CONSTANT:
			case STRING_CONSTANT:
			case OPEN_CURLY:
				{
				State = 213;
				constant();
				}
				break;
			case REF_CONSTANT:
				{
				State = 214;
				Match(REF_CONSTANT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 224;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 217;
				Match(COMMA);
				State = 220;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NONREF_ERRORS:
				case LOGICAL_CONSTANT:
				case NUMERICAL_CONSTANT:
				case STRING_CONSTANT:
				case OPEN_CURLY:
					{
					State = 218;
					constant();
					}
					break;
				case REF_CONSTANT:
					{
					State = 219;
					Match(REF_CONSTANT);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				}
				State = 226;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cell_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public A1_referenceContext a1_reference() {
			return GetRuleContext<A1_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BANG_REFERENCE() { return GetToken(FormulaParser.BANG_REFERENCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SHEET_RANGE_PREFIX() { return GetToken(FormulaParser.SHEET_RANGE_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_SHEET_PREFIX() { return GetToken(FormulaParser.SINGLE_SHEET_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_CONSTANT() { return GetToken(FormulaParser.REF_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(FormulaParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FormulaParser.COLON, 0); }
		public Cell_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cell_reference; } }
	}

	[RuleVersion(0)]
	public Cell_referenceContext cell_reference() {
		Cell_referenceContext _localctx = new Cell_referenceContext(Context, State);
		EnterRule(_localctx, 36, RULE_cell_reference);
		try {
			State = 240;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case A1_CELL:
			case A1_SPAN_REFERENCE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 227;
				a1_reference();
				}
				break;
			case BANG_REFERENCE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 228;
				Match(BANG_REFERENCE);
				}
				break;
			case SHEET_RANGE_PREFIX:
				EnterOuterAlt(_localctx, 3);
				{
				State = 229;
				Match(SHEET_RANGE_PREFIX);
				State = 230;
				a1_reference();
				}
				break;
			case SINGLE_SHEET_PREFIX:
				EnterOuterAlt(_localctx, 4);
				{
				State = 231;
				Match(SINGLE_SHEET_PREFIX);
				State = 234;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case A1_CELL:
				case A1_SPAN_REFERENCE:
					{
					State = 232;
					a1_reference();
					}
					break;
				case REF_CONSTANT:
					{
					State = 233;
					Match(REF_CONSTANT);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case NAME:
				EnterOuterAlt(_localctx, 5);
				{
				State = 236;
				Match(NAME);
				State = 237;
				Match(COLON);
				State = 238;
				Match(SINGLE_SHEET_PREFIX);
				State = 239;
				a1_reference();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class A1_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] A1_CELL() { return GetTokens(FormulaParser.A1_CELL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode A1_CELL(int i) {
			return GetToken(FormulaParser.A1_CELL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FormulaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode A1_SPAN_REFERENCE() { return GetToken(FormulaParser.A1_SPAN_REFERENCE, 0); }
		public A1_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_a1_reference; } }
	}

	[RuleVersion(0)]
	public A1_referenceContext a1_reference() {
		A1_referenceContext _localctx = new A1_referenceContext(Context, State);
		EnterRule(_localctx, 38, RULE_a1_reference);
		try {
			State = 247;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 242;
				Match(A1_CELL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 243;
				Match(A1_CELL);
				State = 244;
				Match(COLON);
				State = 245;
				Match(A1_CELL);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 246;
				Match(A1_SPAN_REFERENCE);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Argument_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Arg_expressionContext[] arg_expression() {
			return GetRuleContexts<Arg_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_expressionContext arg_expression(int i) {
			return GetRuleContext<Arg_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(FormulaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(FormulaParser.COMMA, i);
		}
		public Argument_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument_list; } }
	}

	[RuleVersion(0)]
	public Argument_listContext argument_list() {
		Argument_listContext _localctx = new Argument_listContext(Context, State);
		EnterRule(_localctx, 40, RULE_argument_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				{
				State = 249;
				arg_expression();
				}
				break;
			}
			State = 258;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 252;
				Match(COMMA);
				State = 254;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
				case 1:
					{
					State = 253;
					arg_expression();
					}
					break;
				}
				}
				}
				State = 260;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 261;
			Match(CLOSE_BRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_concat_expressionContext[] arg_concat_expression() {
			return GetRuleContexts<Arg_concat_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_concat_expressionContext arg_concat_expression(int i) {
			return GetRuleContext<Arg_concat_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_OR_EQUAL_THAN() { return GetTokens(FormulaParser.GREATER_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.GREATER_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_OR_EQUAL_THAN() { return GetTokens(FormulaParser.LESS_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.LESS_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_THAN() { return GetTokens(FormulaParser.LESS_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_THAN(int i) {
			return GetToken(FormulaParser.LESS_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_THAN() { return GetTokens(FormulaParser.GREATER_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_THAN(int i) {
			return GetToken(FormulaParser.GREATER_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NOT_EQUAL() { return GetTokens(FormulaParser.NOT_EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT_EQUAL(int i) {
			return GetToken(FormulaParser.NOT_EQUAL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] EQUAL() { return GetTokens(FormulaParser.EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL(int i) {
			return GetToken(FormulaParser.EQUAL, i);
		}
		public Arg_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_expression; } }
	}

	[RuleVersion(0)]
	public Arg_expressionContext arg_expression() {
		Arg_expressionContext _localctx = new Arg_expressionContext(Context, State);
		EnterRule(_localctx, 42, RULE_arg_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 263;
			arg_concat_expression();
			State = 268;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) {
				{
				{
				State = 264;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 265;
				arg_concat_expression();
				}
				}
				State = 270;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_concat_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_additive_expressionContext[] arg_additive_expression() {
			return GetRuleContexts<Arg_additive_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_additive_expressionContext arg_additive_expression(int i) {
			return GetRuleContext<Arg_additive_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CONCAT() { return GetTokens(FormulaParser.CONCAT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONCAT(int i) {
			return GetToken(FormulaParser.CONCAT, i);
		}
		public Arg_concat_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_concat_expression; } }
	}

	[RuleVersion(0)]
	public Arg_concat_expressionContext arg_concat_expression() {
		Arg_concat_expressionContext _localctx = new Arg_concat_expressionContext(Context, State);
		EnterRule(_localctx, 44, RULE_arg_concat_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 271;
			arg_additive_expression();
			State = 276;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CONCAT) {
				{
				{
				State = 272;
				Match(CONCAT);
				State = 273;
				arg_additive_expression();
				}
				}
				State = 278;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_additive_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_multiplying_expressionContext[] arg_multiplying_expression() {
			return GetRuleContexts<Arg_multiplying_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_multiplying_expressionContext arg_multiplying_expression(int i) {
			return GetRuleContext<Arg_multiplying_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PLUS() { return GetTokens(FormulaParser.PLUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS(int i) {
			return GetToken(FormulaParser.PLUS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MINUS() { return GetTokens(FormulaParser.MINUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS(int i) {
			return GetToken(FormulaParser.MINUS, i);
		}
		public Arg_additive_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_additive_expression; } }
	}

	[RuleVersion(0)]
	public Arg_additive_expressionContext arg_additive_expression() {
		Arg_additive_expressionContext _localctx = new Arg_additive_expressionContext(Context, State);
		EnterRule(_localctx, 46, RULE_arg_additive_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			arg_multiplying_expression();
			State = 284;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PLUS || _la==MINUS) {
				{
				{
				State = 280;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 281;
				arg_multiplying_expression();
				}
				}
				State = 286;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_multiplying_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_pow_expressionContext[] arg_pow_expression() {
			return GetRuleContexts<Arg_pow_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_pow_expressionContext arg_pow_expression(int i) {
			return GetRuleContext<Arg_pow_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MULT() { return GetTokens(FormulaParser.MULT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT(int i) {
			return GetToken(FormulaParser.MULT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DIV() { return GetTokens(FormulaParser.DIV); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV(int i) {
			return GetToken(FormulaParser.DIV, i);
		}
		public Arg_multiplying_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_multiplying_expression; } }
	}

	[RuleVersion(0)]
	public Arg_multiplying_expressionContext arg_multiplying_expression() {
		Arg_multiplying_expressionContext _localctx = new Arg_multiplying_expressionContext(Context, State);
		EnterRule(_localctx, 48, RULE_arg_multiplying_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 287;
			arg_pow_expression();
			State = 292;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==MULT || _la==DIV) {
				{
				{
				State = 288;
				_la = TokenStream.LA(1);
				if ( !(_la==MULT || _la==DIV) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 289;
				arg_pow_expression();
				}
				}
				State = 294;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_pow_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_percent_expressionContext[] arg_percent_expression() {
			return GetRuleContexts<Arg_percent_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_percent_expressionContext arg_percent_expression(int i) {
			return GetRuleContext<Arg_percent_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] POW() { return GetTokens(FormulaParser.POW); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POW(int i) {
			return GetToken(FormulaParser.POW, i);
		}
		public Arg_pow_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_pow_expression; } }
	}

	[RuleVersion(0)]
	public Arg_pow_expressionContext arg_pow_expression() {
		Arg_pow_expressionContext _localctx = new Arg_pow_expressionContext(Context, State);
		EnterRule(_localctx, 50, RULE_arg_pow_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 295;
			arg_percent_expression();
			State = 300;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==POW) {
				{
				{
				State = 296;
				Match(POW);
				State = 297;
				arg_percent_expression();
				}
				}
				State = 302;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_percent_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_prefix_atom_expressionContext arg_prefix_atom_expression() {
			return GetRuleContext<Arg_prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PERCENT() { return GetToken(FormulaParser.PERCENT, 0); }
		public Arg_percent_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_percent_expression; } }
	}

	[RuleVersion(0)]
	public Arg_percent_expressionContext arg_percent_expression() {
		Arg_percent_expressionContext _localctx = new Arg_percent_expressionContext(Context, State);
		EnterRule(_localctx, 52, RULE_arg_percent_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 303;
			arg_prefix_atom_expression();
			State = 305;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PERCENT) {
				{
				State = 304;
				Match(PERCENT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_prefix_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_prefix_atom_expressionContext arg_prefix_atom_expression() {
			return GetRuleContext<Arg_prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(FormulaParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(FormulaParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Arg_atom_expressionContext arg_atom_expression() {
			return GetRuleContext<Arg_atom_expressionContext>(0);
		}
		public Arg_prefix_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_prefix_atom_expression; } }
	}

	[RuleVersion(0)]
	public Arg_prefix_atom_expressionContext arg_prefix_atom_expression() {
		Arg_prefix_atom_expressionContext _localctx = new Arg_prefix_atom_expressionContext(Context, State);
		EnterRule(_localctx, 54, RULE_arg_prefix_atom_expression);
		int _la;
		try {
			State = 310;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,34,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 307;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 308;
				arg_prefix_atom_expression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 309;
				arg_atom_expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext constant() {
			return GetRuleContext<ConstantContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_BRACE() { return GetToken(FormulaParser.OPEN_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Function_callContext function_call() {
			return GetRuleContext<Function_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression() {
			return GetRuleContext<Ref_implicit_expressionContext>(0);
		}
		public Arg_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_atom_expression; } }
	}

	[RuleVersion(0)]
	public Arg_atom_expressionContext arg_atom_expression() {
		Arg_atom_expressionContext _localctx = new Arg_atom_expressionContext(Context, State);
		EnterRule(_localctx, 56, RULE_arg_atom_expression);
		try {
			State = 319;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,35,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 312;
				constant();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 313;
				Match(OPEN_BRACE);
				State = 314;
				expression();
				State = 315;
				Match(CLOSE_BRACE);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 317;
				function_call();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 318;
				ref_implicit_expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(FormulaParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_SHEET_PREFIX() { return GetToken(FormulaParser.SINGLE_SHEET_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOK_PREFIX() { return GetToken(FormulaParser.BOOK_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BANG_NAME() { return GetToken(FormulaParser.BANG_NAME, 0); }
		public Name_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_reference; } }
	}

	[RuleVersion(0)]
	public Name_referenceContext name_reference() {
		Name_referenceContext _localctx = new Name_referenceContext(Context, State);
		EnterRule(_localctx, 58, RULE_name_reference);
		int _la;
		try {
			State = 326;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,36,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 321;
				Match(NAME);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 322;
				_la = TokenStream.LA(1);
				if ( !(_la==BOOK_PREFIX || _la==SINGLE_SHEET_PREFIX) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 323;
				Match(NAME);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 324;
				if (!(IsBangName(CurrentToken.Text))) throw new FailedPredicateException(this, "IsBangName(CurrentToken.Text)");
				State = 325;
				Match(BANG_NAME);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Dde_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOK_PREFIX() { return GetToken(FormulaParser.BOOK_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DDE_ITEM() { return GetToken(FormulaParser.DDE_ITEM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_SHEET_PREFIX() { return GetToken(FormulaParser.SINGLE_SHEET_PREFIX, 0); }
		public Dde_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dde_reference; } }
	}

	[RuleVersion(0)]
	public Dde_referenceContext dde_reference() {
		Dde_referenceContext _localctx = new Dde_referenceContext(Context, State);
		EnterRule(_localctx, 60, RULE_dde_reference);
		try {
			State = 333;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,37,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 328;
				Match(BOOK_PREFIX);
				State = 329;
				Match(DDE_ITEM);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 330;
				if (!(IsDdeLinkPrefix(CurrentToken.Text))) throw new FailedPredicateException(this, "IsDdeLinkPrefix(CurrentToken.Text)");
				State = 331;
				Match(SINGLE_SHEET_PREFIX);
				State = 332;
				Match(DDE_ITEM);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Structure_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTRA_TABLE_REFERENCE() { return GetToken(FormulaParser.INTRA_TABLE_REFERENCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Table_identifierContext table_identifier() {
			return GetRuleContext<Table_identifierContext>(0);
		}
		public Structure_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structure_reference; } }
	}

	[RuleVersion(0)]
	public Structure_referenceContext structure_reference() {
		Structure_referenceContext _localctx = new Structure_referenceContext(Context, State);
		EnterRule(_localctx, 62, RULE_structure_reference);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 336;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==BOOK_PREFIX || _la==NAME) {
				{
				State = 335;
				table_identifier();
				}
			}

			State = 338;
			Match(INTRA_TABLE_REFERENCE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_identifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Table_nameContext table_name() {
			return GetRuleContext<Table_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOK_PREFIX() { return GetToken(FormulaParser.BOOK_PREFIX, 0); }
		public Table_identifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_identifier; } }
	}

	[RuleVersion(0)]
	public Table_identifierContext table_identifier() {
		Table_identifierContext _localctx = new Table_identifierContext(Context, State);
		EnterRule(_localctx, 64, RULE_table_identifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 341;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==BOOK_PREFIX) {
				{
				State = 340;
				Match(BOOK_PREFIX);
				}
			}

			State = 343;
			table_name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(FormulaParser.NAME, 0); }
		public Table_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_name; } }
	}

	[RuleVersion(0)]
	public Table_nameContext table_name() {
		Table_nameContext _localctx = new Table_nameContext(Context, State);
		EnterRule(_localctx, 66, RULE_table_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 345;
			Match(NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_function_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_FUNCTION_LIST() { return GetToken(FormulaParser.REF_FUNCTION_LIST, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Argument_listContext argument_list() {
			return GetRuleContext<Argument_listContext>(0);
		}
		public Ref_function_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_function_call; } }
	}

	[RuleVersion(0)]
	public Ref_function_callContext ref_function_call() {
		Ref_function_callContext _localctx = new Ref_function_callContext(Context, State);
		EnterRule(_localctx, 68, RULE_ref_function_call);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 347;
			Match(REF_FUNCTION_LIST);
			State = 348;
			argument_list();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Argument_listContext argument_list() {
			return GetRuleContext<Argument_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CELL_FUNCTION_LIST() { return GetToken(FormulaParser.CELL_FUNCTION_LIST, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USER_DEFINED_FUNCTION_NAME() { return GetToken(FormulaParser.USER_DEFINED_FUNCTION_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_SHEET_PREFIX() { return GetToken(FormulaParser.SINGLE_SHEET_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOK_PREFIX() { return GetToken(FormulaParser.BOOK_PREFIX, 0); }
		public Function_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_call; } }
	}

	[RuleVersion(0)]
	public Function_callContext function_call() {
		Function_callContext _localctx = new Function_callContext(Context, State);
		EnterRule(_localctx, 70, RULE_function_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 355;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case CELL_FUNCTION_LIST:
				{
				State = 350;
				Match(CELL_FUNCTION_LIST);
				}
				break;
			case BOOK_PREFIX:
			case SINGLE_SHEET_PREFIX:
			case USER_DEFINED_FUNCTION_NAME:
				{
				State = 352;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==BOOK_PREFIX || _la==SINGLE_SHEET_PREFIX) {
					{
					State = 351;
					_la = TokenStream.LA(1);
					if ( !(_la==BOOK_PREFIX || _la==SINGLE_SHEET_PREFIX) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 354;
				Match(USER_DEFINED_FUNCTION_NAME);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 357;
			argument_list();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 11: return ref_intersection_expression_sempred((Ref_intersection_expressionContext)_localctx, predIndex);
		case 29: return name_reference_sempred((Name_referenceContext)_localctx, predIndex);
		case 30: return dde_reference_sempred((Dde_referenceContext)_localctx, predIndex);
		}
		return true;
	}
	private bool ref_intersection_expression_sempred(Ref_intersection_expressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return IsSpaceBeforeAt(CurrentToken.Text);
		}
		return true;
	}
	private bool name_reference_sempred(Name_referenceContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return IsBangName(CurrentToken.Text);
		}
		return true;
	}
	private bool dde_reference_sempred(Dde_referenceContext _localctx, int predIndex) {
		switch (predIndex) {
		case 2: return IsDdeLinkPrefix(CurrentToken.Text);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,41,360,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,2,35,7,35,
		1,0,1,0,1,0,1,1,1,1,1,1,5,1,79,8,1,10,1,12,1,82,9,1,1,2,1,2,1,2,5,2,87,
		8,2,10,2,12,2,90,9,2,1,3,1,3,1,3,5,3,95,8,3,10,3,12,3,98,9,3,1,4,1,4,1,
		4,5,4,103,8,4,10,4,12,4,106,9,4,1,5,1,5,1,5,5,5,111,8,5,10,5,12,5,114,
		9,5,1,6,1,6,5,6,118,8,6,10,6,12,6,121,9,6,1,7,1,7,1,7,3,7,126,8,7,1,8,
		1,8,1,8,1,8,1,8,1,8,1,8,3,8,135,8,8,1,9,1,9,1,9,5,9,140,8,9,10,9,12,9,
		143,9,9,1,10,1,10,1,10,3,10,148,8,10,1,11,1,11,1,11,5,11,153,8,11,10,11,
		12,11,156,9,11,1,11,1,11,1,11,3,11,161,8,11,1,12,1,12,1,12,5,12,166,8,
		12,10,12,12,12,169,9,12,1,12,1,12,1,12,3,12,174,8,12,1,13,1,13,3,13,178,
		8,13,1,14,1,14,1,14,3,14,183,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,3,14,194,8,14,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,204,
		8,15,1,16,1,16,1,16,5,16,209,8,16,10,16,12,16,212,9,16,1,17,1,17,3,17,
		216,8,17,1,17,1,17,1,17,3,17,221,8,17,5,17,223,8,17,10,17,12,17,226,9,
		17,1,18,1,18,1,18,1,18,1,18,1,18,1,18,3,18,235,8,18,1,18,1,18,1,18,1,18,
		3,18,241,8,18,1,19,1,19,1,19,1,19,1,19,3,19,248,8,19,1,20,3,20,251,8,20,
		1,20,1,20,3,20,255,8,20,5,20,257,8,20,10,20,12,20,260,9,20,1,20,1,20,1,
		21,1,21,1,21,5,21,267,8,21,10,21,12,21,270,9,21,1,22,1,22,1,22,5,22,275,
		8,22,10,22,12,22,278,9,22,1,23,1,23,1,23,5,23,283,8,23,10,23,12,23,286,
		9,23,1,24,1,24,1,24,5,24,291,8,24,10,24,12,24,294,9,24,1,25,1,25,1,25,
		5,25,299,8,25,10,25,12,25,302,9,25,1,26,1,26,3,26,306,8,26,1,27,1,27,1,
		27,3,27,311,8,27,1,28,1,28,1,28,1,28,1,28,1,28,1,28,3,28,320,8,28,1,29,
		1,29,1,29,1,29,1,29,3,29,327,8,29,1,30,1,30,1,30,1,30,1,30,3,30,334,8,
		30,1,31,3,31,337,8,31,1,31,1,31,1,32,3,32,342,8,32,1,32,1,32,1,33,1,33,
		1,34,1,34,1,34,1,35,1,35,3,35,353,8,35,1,35,3,35,356,8,35,1,35,1,35,1,
		35,0,0,36,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,
		44,46,48,50,52,54,56,58,60,62,64,66,68,70,0,4,1,0,12,17,1,0,9,10,1,0,7,
		8,2,0,29,29,32,32,383,0,72,1,0,0,0,2,75,1,0,0,0,4,83,1,0,0,0,6,91,1,0,
		0,0,8,99,1,0,0,0,10,107,1,0,0,0,12,115,1,0,0,0,14,125,1,0,0,0,16,134,1,
		0,0,0,18,136,1,0,0,0,20,147,1,0,0,0,22,149,1,0,0,0,24,162,1,0,0,0,26,175,
		1,0,0,0,28,193,1,0,0,0,30,203,1,0,0,0,32,205,1,0,0,0,34,215,1,0,0,0,36,
		240,1,0,0,0,38,247,1,0,0,0,40,250,1,0,0,0,42,263,1,0,0,0,44,271,1,0,0,
		0,46,279,1,0,0,0,48,287,1,0,0,0,50,295,1,0,0,0,52,303,1,0,0,0,54,310,1,
		0,0,0,56,319,1,0,0,0,58,326,1,0,0,0,60,333,1,0,0,0,62,336,1,0,0,0,64,341,
		1,0,0,0,66,345,1,0,0,0,68,347,1,0,0,0,70,355,1,0,0,0,72,73,3,2,1,0,73,
		74,5,0,0,1,74,1,1,0,0,0,75,80,3,4,2,0,76,77,7,0,0,0,77,79,3,4,2,0,78,76,
		1,0,0,0,79,82,1,0,0,0,80,78,1,0,0,0,80,81,1,0,0,0,81,3,1,0,0,0,82,80,1,
		0,0,0,83,88,3,6,3,0,84,85,5,11,0,0,85,87,3,6,3,0,86,84,1,0,0,0,87,90,1,
		0,0,0,88,86,1,0,0,0,88,89,1,0,0,0,89,5,1,0,0,0,90,88,1,0,0,0,91,96,3,8,
		4,0,92,93,7,1,0,0,93,95,3,8,4,0,94,92,1,0,0,0,95,98,1,0,0,0,96,94,1,0,
		0,0,96,97,1,0,0,0,97,7,1,0,0,0,98,96,1,0,0,0,99,104,3,10,5,0,100,101,7,
		2,0,0,101,103,3,10,5,0,102,100,1,0,0,0,103,106,1,0,0,0,104,102,1,0,0,0,
		104,105,1,0,0,0,105,9,1,0,0,0,106,104,1,0,0,0,107,112,3,12,6,0,108,109,
		5,6,0,0,109,111,3,12,6,0,110,108,1,0,0,0,111,114,1,0,0,0,112,110,1,0,0,
		0,112,113,1,0,0,0,113,11,1,0,0,0,114,112,1,0,0,0,115,119,3,14,7,0,116,
		118,5,18,0,0,117,116,1,0,0,0,118,121,1,0,0,0,119,117,1,0,0,0,119,120,1,
		0,0,0,120,13,1,0,0,0,121,119,1,0,0,0,122,123,7,1,0,0,123,126,3,14,7,0,
		124,126,3,16,8,0,125,122,1,0,0,0,125,124,1,0,0,0,126,15,1,0,0,0,127,135,
		3,30,15,0,128,129,5,21,0,0,129,130,3,2,1,0,130,131,5,22,0,0,131,135,1,
		0,0,0,132,135,3,70,35,0,133,135,3,18,9,0,134,127,1,0,0,0,134,128,1,0,0,
		0,134,132,1,0,0,0,134,133,1,0,0,0,135,17,1,0,0,0,136,141,3,20,10,0,137,
		138,5,25,0,0,138,140,3,20,10,0,139,137,1,0,0,0,140,143,1,0,0,0,141,139,
		1,0,0,0,141,142,1,0,0,0,142,19,1,0,0,0,143,141,1,0,0,0,144,145,5,27,0,
		0,145,148,3,20,10,0,146,148,3,22,11,0,147,144,1,0,0,0,147,146,1,0,0,0,
		148,21,1,0,0,0,149,154,3,24,12,0,150,151,5,26,0,0,151,153,3,24,12,0,152,
		150,1,0,0,0,153,156,1,0,0,0,154,152,1,0,0,0,154,155,1,0,0,0,155,160,1,
		0,0,0,156,154,1,0,0,0,157,158,4,11,0,0,158,159,5,27,0,0,159,161,3,20,10,
		0,160,157,1,0,0,0,160,161,1,0,0,0,161,23,1,0,0,0,162,167,3,26,13,0,163,
		164,5,20,0,0,164,166,3,26,13,0,165,163,1,0,0,0,166,169,1,0,0,0,167,165,
		1,0,0,0,167,168,1,0,0,0,168,173,1,0,0,0,169,167,1,0,0,0,170,171,5,20,0,
		0,171,172,5,27,0,0,172,174,3,20,10,0,173,170,1,0,0,0,173,174,1,0,0,0,174,
		25,1,0,0,0,175,177,3,28,14,0,176,178,5,28,0,0,177,176,1,0,0,0,177,178,
		1,0,0,0,178,27,1,0,0,0,179,182,5,1,0,0,180,183,3,38,19,0,181,183,5,1,0,
		0,182,180,1,0,0,0,182,181,1,0,0,0,182,183,1,0,0,0,183,194,1,0,0,0,184,
		185,5,21,0,0,185,186,3,18,9,0,186,187,5,22,0,0,187,194,1,0,0,0,188,194,
		3,36,18,0,189,194,3,68,34,0,190,194,3,58,29,0,191,194,3,62,31,0,192,194,
		3,60,30,0,193,179,1,0,0,0,193,184,1,0,0,0,193,188,1,0,0,0,193,189,1,0,
		0,0,193,190,1,0,0,0,193,191,1,0,0,0,193,192,1,0,0,0,194,29,1,0,0,0,195,
		204,5,2,0,0,196,204,5,3,0,0,197,204,5,4,0,0,198,204,5,5,0,0,199,200,5,
		23,0,0,200,201,3,32,16,0,201,202,5,24,0,0,202,204,1,0,0,0,203,195,1,0,
		0,0,203,196,1,0,0,0,203,197,1,0,0,0,203,198,1,0,0,0,203,199,1,0,0,0,204,
		31,1,0,0,0,205,210,3,34,17,0,206,207,5,19,0,0,207,209,3,34,17,0,208,206,
		1,0,0,0,209,212,1,0,0,0,210,208,1,0,0,0,210,211,1,0,0,0,211,33,1,0,0,0,
		212,210,1,0,0,0,213,216,3,30,15,0,214,216,5,1,0,0,215,213,1,0,0,0,215,
		214,1,0,0,0,216,224,1,0,0,0,217,220,5,25,0,0,218,221,3,30,15,0,219,221,
		5,1,0,0,220,218,1,0,0,0,220,219,1,0,0,0,221,223,1,0,0,0,222,217,1,0,0,
		0,223,226,1,0,0,0,224,222,1,0,0,0,224,225,1,0,0,0,225,35,1,0,0,0,226,224,
		1,0,0,0,227,241,3,38,19,0,228,241,5,30,0,0,229,230,5,31,0,0,230,241,3,
		38,19,0,231,234,5,32,0,0,232,235,3,38,19,0,233,235,5,1,0,0,234,232,1,0,
		0,0,234,233,1,0,0,0,235,241,1,0,0,0,236,237,5,38,0,0,237,238,5,20,0,0,
		238,239,5,32,0,0,239,241,3,38,19,0,240,227,1,0,0,0,240,228,1,0,0,0,240,
		229,1,0,0,0,240,231,1,0,0,0,240,236,1,0,0,0,241,37,1,0,0,0,242,248,5,33,
		0,0,243,244,5,33,0,0,244,245,5,20,0,0,245,248,5,33,0,0,246,248,5,34,0,
		0,247,242,1,0,0,0,247,243,1,0,0,0,247,246,1,0,0,0,248,39,1,0,0,0,249,251,
		3,42,21,0,250,249,1,0,0,0,250,251,1,0,0,0,251,258,1,0,0,0,252,254,5,25,
		0,0,253,255,3,42,21,0,254,253,1,0,0,0,254,255,1,0,0,0,255,257,1,0,0,0,
		256,252,1,0,0,0,257,260,1,0,0,0,258,256,1,0,0,0,258,259,1,0,0,0,259,261,
		1,0,0,0,260,258,1,0,0,0,261,262,5,22,0,0,262,41,1,0,0,0,263,268,3,44,22,
		0,264,265,7,0,0,0,265,267,3,44,22,0,266,264,1,0,0,0,267,270,1,0,0,0,268,
		266,1,0,0,0,268,269,1,0,0,0,269,43,1,0,0,0,270,268,1,0,0,0,271,276,3,46,
		23,0,272,273,5,11,0,0,273,275,3,46,23,0,274,272,1,0,0,0,275,278,1,0,0,
		0,276,274,1,0,0,0,276,277,1,0,0,0,277,45,1,0,0,0,278,276,1,0,0,0,279,284,
		3,48,24,0,280,281,7,1,0,0,281,283,3,48,24,0,282,280,1,0,0,0,283,286,1,
		0,0,0,284,282,1,0,0,0,284,285,1,0,0,0,285,47,1,0,0,0,286,284,1,0,0,0,287,
		292,3,50,25,0,288,289,7,2,0,0,289,291,3,50,25,0,290,288,1,0,0,0,291,294,
		1,0,0,0,292,290,1,0,0,0,292,293,1,0,0,0,293,49,1,0,0,0,294,292,1,0,0,0,
		295,300,3,52,26,0,296,297,5,6,0,0,297,299,3,52,26,0,298,296,1,0,0,0,299,
		302,1,0,0,0,300,298,1,0,0,0,300,301,1,0,0,0,301,51,1,0,0,0,302,300,1,0,
		0,0,303,305,3,54,27,0,304,306,5,18,0,0,305,304,1,0,0,0,305,306,1,0,0,0,
		306,53,1,0,0,0,307,308,7,1,0,0,308,311,3,54,27,0,309,311,3,56,28,0,310,
		307,1,0,0,0,310,309,1,0,0,0,311,55,1,0,0,0,312,320,3,30,15,0,313,314,5,
		21,0,0,314,315,3,2,1,0,315,316,5,22,0,0,316,320,1,0,0,0,317,320,3,70,35,
		0,318,320,3,20,10,0,319,312,1,0,0,0,319,313,1,0,0,0,319,317,1,0,0,0,319,
		318,1,0,0,0,320,57,1,0,0,0,321,327,5,38,0,0,322,323,7,3,0,0,323,327,5,
		38,0,0,324,325,4,29,1,0,325,327,5,41,0,0,326,321,1,0,0,0,326,322,1,0,0,
		0,326,324,1,0,0,0,327,59,1,0,0,0,328,329,5,29,0,0,329,334,5,40,0,0,330,
		331,4,30,2,0,331,332,5,32,0,0,332,334,5,40,0,0,333,328,1,0,0,0,333,330,
		1,0,0,0,334,61,1,0,0,0,335,337,3,64,32,0,336,335,1,0,0,0,336,337,1,0,0,
		0,337,338,1,0,0,0,338,339,5,39,0,0,339,63,1,0,0,0,340,342,5,29,0,0,341,
		340,1,0,0,0,341,342,1,0,0,0,342,343,1,0,0,0,343,344,3,66,33,0,344,65,1,
		0,0,0,345,346,5,38,0,0,346,67,1,0,0,0,347,348,5,35,0,0,348,349,3,40,20,
		0,349,69,1,0,0,0,350,356,5,36,0,0,351,353,7,3,0,0,352,351,1,0,0,0,352,
		353,1,0,0,0,353,354,1,0,0,0,354,356,5,37,0,0,355,350,1,0,0,0,355,352,1,
		0,0,0,356,357,1,0,0,0,357,358,3,40,20,0,358,71,1,0,0,0,42,80,88,96,104,
		112,119,125,134,141,147,154,160,167,173,177,182,193,203,210,215,220,224,
		234,240,247,250,254,258,268,276,284,292,300,305,310,319,326,333,336,341,
		352,355
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
